### ISSUE TITLE
SsrProxy works only for html pages

### ISSUE THREAD

**Issue by realdigger** [Tpessia/ssr-proxy-js#1]
SsrProxy works only for urls like http://mysite.xyz/home/index.html
How to enable it for urls without html extension like http://mysite.xyz/home/ ?

**Comment by Tpessia** [comment]
Hi @realdigger!

You should be able to configure when to SsrProxy with the SsrProxyConfig.ssr.shouldUse function, configured when you start a new SrrProxy instance.

This is the default behavior:

```javascript
params => params.isBot && (/\.html$/.test(params.targetUrl) || !/\./.test(params.targetUrl))
```

Which probably disables SSR in your case because of the second rule of the or clause, that matches the "." on the domain name. The code bellow could be a easy fix, but make sure to test it for other use cases:

```javascript
params => params.isBot && (/\.html$/.test(params.targetUrl) || !/\./.test(new URL(params.targetUrl).pathname))
```

Hope it helps! If it doesn't, please send me the configuration you are use so I can try to help further!
